Implement bash translator
nteract/papermill pull request #674
Opened 2022-07-03 17:57 UTC by kdm9

## Support translation of parameters to bash/*NIX shell

Thanks for papermill! I have used it for python notebooks, but a lot of my work is best done in shell, for which I use jupyter notebooks with the [bash_kernel](https://github.com/takluyver/bash_kernel/) (via *.sh scripts and jupytext). 

Alas papermill doesn't seem to support bash/shell script, due to a hitherto unimplemented bash translator. This PR implements a `BashTranslator`, and therefore enables bash kernel notebooks to be parametrised.  This code supports `str`, `list`, `bool`[^1], `None`, `int`, and `float` parameter values. Dict could in theory be supported via [associative arrays](https://linuxhint.com/associative_arrays_bash_examples/) but for now they are not implemented[^2].

For a functioning example, please see the attached notebook.

Best,
K

[^1]: Bash doesn't really have a bool type, but `true` and `false` are at least common and sensible string constants for truthy-ness and falsy-ness. See for example [this SO answer](https://stackoverflow.com/a/21210966).
[^2]: Associative arrays require quite recent bash versions, and I've never seen them used outside tutorials. Supporting them would also likely require a more involved code path as one must pre-declare an associative array in bash, and then declare one entry per line (see link above).

2022-07-03 18:05 UTC, kdm9 commented
Alas GH doesn't support attaching *.ipynb, so I have had to rename it *.txt, but here's the test notebook.

[test.ipynb.txt](https://github.com/nteract/papermill/files/9035277/test.ipynb.txt)

The following params.yml can be used with this:

```
say: "Write a book"
people:
  - Alice
  - Bob
  - Robert'); DROP TABLE students;-- # XKCD's favourite son
```

2022-08-03 11:37 UTC, kdm9 commented
A friendly ping to the nteract team about this PR. All tests pass locally, and this is currently blocking us from using papermill in our analyses.

2022-08-12 22:59 UTC, rohitsanj requested changes
Thanks for the PR, @kdm9! Can you please add some tests to [`test_translators.py`](https://github.com/nteract/papermill/blob/main/papermill/tests/test_translators.py).

2022-08-13 09:17 UTC, kdm9 commented
@rohitsanj tests implemented and passing. There are some unrelated failures on my machine, all to do with the google cloud interaction, which I assume is because I don't have a GCS environment correctly configured. Any chance you can allow the CI to run on this PR, so we can see if all is green in a well-configured environment?

2022-08-14 22:07 UTC, MSeal approved these changes
Thanks for adding tests! They passed on the CI chain so no worries about local dev issues there

2022-08-14 22:08 UTC, merged